--- # ------------------------------------------------------------------------------------

# ------------------------------------------------------------------------------------
# Pages Properties
# - id: the unique (survey-wide) ID of the page
# - path: the page's path
# - children: the page's children pages
# - blocks: the page's blocks
# - pageTemplate: a template from which to inherit its properties (not used)
# - showTitle: whether to show the page title or not
# - variables: page variables (compiled during sitemap generation)

# Block Properties
# - id: the unique (survey-wide) ID of the block
# - blockName: the name of the block (used for titles, descriptions, etc.)
# - bucketKeysName: the name of the block's keys (used for legends, formatting data, etc.)
# - blockType: the type of block (which component to use)
# - query: the query used to populate the block's data
# - dataPath: the path to use (from the query root) to access the block's data
# - showLegend: whether to show the block's legend
# - showDescription: whether to show the block's description
# - template: a template from which to inherit its properties
# - translateData: whether to try and translate
# - queryVariables: GraphQL query variables (handled by GraphQL)
# - variables: block variables (compiled during sitemap generation)

- id: introduction
  path: /
  showTitle: false
  blocks:
      - id: survey_intro
        blockType: SurveyIntroBlock
      - id: survey_newsletter
        blockType: NewsletterBlock
      - id: survey_sponsors
        blockType: SponsorsBlock
      - id: survey_translators
        blockType: TranslatorsBlock

- id: tshirt
  path: /tshirt
  showTitle: false
  blocks:
      - id: tshirt_intro
        template: pageIntroductionTemplate
      - id: tshirt_block
        blockType: TshirtBlock

- id: user_info
  titleId: sections.demographics.title
  path: /demographics
  blocks:
      - template: pageIntroductionTemplate

      - id: country
        template: demographicsTemplate
        blockType: ParticipationByCountryBlock

      - id: locale
        template: demographicsTemplate
        blockType: HorizontalBarBlock
        translateData: true

      - id: yearly_salary
        template: demographicsTemplate

      - id: years_of_experience
        template: demographicsTemplate

      - id: company_size
        template: demographicsTemplate

      - id: source
        template: sourceTemplate
        blockType: HorizontalBarBlock

      - id: gender
        template: demographicsTemplate
        showLegend: true
        blockType: GenderBlock

      - id: race_ethnicity
        template: demographicsTemplate
        blockType: HorizontalBarBlock
        translateData: true

      - id: job_title
        template: demographicsTemplate
        blockType: HorizontalBarBlock
        translateData: true

      - id: css_proficiency
        template: proficiencyTemplate

      - id: javascript_proficiency
        template: proficiencyTemplate

      - id: backend_proficiency
        template: proficiencyTemplate

      - items: [fm-homepage]
        template: recommendedResourcesTemplate

#- id: overview
#  path: /overview
#  blocks:
#      - id: overviewIntroduction
#        template: pageIntroductionTemplate
#        variables:
#            pageId: '${id}'
#      - id: toolsArrow
#        template: toolsArrowsTemplate
#      - id: scatterplotOverview
#        template: scatterplotOverviewTemplate
#      - id: overview_recommended_resources
#        template: recommendedResourcesTemplate
#        sponsors:
#            - fullstack-d3

- id: features
  path: /features
  blocks:
      - template: pageIntroductionTemplate

      - template: featuresOverviewTemplate

      - template: knowledgeScoreTemplate

      - items: [fm-learncss]
        template: recommendedResourcesTemplate

  children:
      - id: syntax
        path: /syntax
        blocks:
            - id: syntax
              template: pageIntroductionTemplate

            - id: destructuring
              template: featureExperienceTemplate

            - id: spread_operator
              template: featureExperienceTemplate

            - id: arrow_functions
              template: featureExperienceTemplate

            - id: nullish_coalescing
              template: featureExperienceTemplate

            - id: optional_chaining
              template: featureExperienceTemplate

            - id: private_fields
              template: featureExperienceTemplate

      - id: language
        path: /language
        blocks:
            - id: language
              template: pageIntroductionTemplate

            - id: proxies
              template: featureExperienceTemplate

            - id: async_await
              template: featureExperienceTemplate

            - id: promises
              template: featureExperienceTemplate

            - id: decorators
              template: featureExperienceTemplate

            - id: promise_all_settled
              template: featureExperienceTemplate

            - id: dynamic_import
              template: featureExperienceTemplate

      - id: data_structures
        path: /data-structures
        blocks:
            - id: data_structures
              template: pageIntroductionTemplate

            - id: maps
              template: featureExperienceTemplate

            - id: sets
              template: featureExperienceTemplate

            - id: typed_arrays
              template: featureExperienceTemplate

            - id: array_prototype_flat
              template: featureExperienceTemplate

            - id: big_int
              template: featureExperienceTemplate

      - id: browser_apis
        path: /browser-apis
        blocks:
            - id: browser_apis
              template: pageIntroductionTemplate

            - id: service_workers
              template: featureExperienceTemplate

            - id: local_storage
              template: featureExperienceTemplate

            - id: intl
              template: featureExperienceTemplate

            - id: web_audio
              template: featureExperienceTemplate

            - id: webgl
              template: featureExperienceTemplate

            - id: web_animations
              template: featureExperienceTemplate

            - id: webrtc
              template: featureExperienceTemplate

            - id: web_speech
              template: featureExperienceTemplate

            - id: webvr
              template: featureExperienceTemplate

            - id: websocket
              template: featureExperienceTemplate

            - id: fetch
              template: featureExperienceTemplate

            - id: custom_elements
              template: featureExperienceTemplate

            - id: shadow_dom
              template: featureExperienceTemplate

      - id: other_features
        path: /other-features
        blocks:
            - id: other_features
              template: pageIntroductionTemplate

            - id: pwa
              template: featureExperienceTemplate

            - id: wasm
              template: featureExperienceTemplate

- id: technologies
  path: /technologies
  blocks:
      - id: technologiesIntroduction
        template: pageIntroductionTemplate

      # - id: scatterplotOverview
      #   template: scatterplotOverviewTemplate

  children:
      - id: javascript_flavors
        path: /javascript-flavors
        variables:
            toolIds: ${toolsCategories.javascript_flavors}
        blocks:
            - template: pageIntroductionTemplate

            - template: toolsExperienceRankingTemplate

            - template: toolsSectionStreamsTemplate

            - template: toolsExperienceMarimekkoTemplate

            # - template: toolsUsageVariationsTemplate

            - id: typescript
              template: toolExperienceTemplate
            - id: reason
              template: toolExperienceTemplate
            - id: elm
              template: toolExperienceTemplate
            - id: clojurescript
              template: toolExperienceTemplate
            - id: purescript
              template: toolExperienceTemplate

            - template: sectionOtherToolsTemplate

            - template: happinessTemplate

      - id: front_end_frameworks
        path: /front-end-frameworks
        variables:
            toolIds: ${toolsCategories.front_end_frameworks}
        blocks:
            - template: pageIntroductionTemplate

            - template: toolsExperienceRankingTemplate

            - template: toolsSectionStreamsTemplate

            - template: toolsExperienceMarimekkoTemplate

            # - template: toolsUsageVariationsTemplate

            - id: react
              template: toolExperienceTemplate
            - id: vue
              template: toolExperienceTemplate
            - id: angular
              template: toolExperienceTemplate
            - id: preact
              template: toolExperienceTemplate
            - id: ember
              template: toolExperienceTemplate
            - id: svelte
              template: toolExperienceTemplate
            - id: alpinejs
              template: toolExperienceTemplate
            - id: litelement
              template: toolExperienceTemplate
            - id: stimulus
              template: toolExperienceTemplate

            - template: sectionOtherToolsTemplate

            - template: happinessTemplate

#       - id: css_methodologies
#         path: /methodologies
#         variables:
#             toolIds: ${toolsCategories.css_methodologies}
#         blocks:
#             - template: pageIntroductionTemplate
#
#             - template: toolsExperienceRankingTemplate
#
#             - template: toolsSectionStreamsTemplate
#
#             - template: toolsExperienceMarimekkoTemplate
#
#             - template: toolsUsageVariationsTemplate
#
#             - id: bem
#               template: toolExperienceTemplate
#             - id: atomic_css
#               template: toolExperienceTemplate
#             - id: oocss
#               template: toolExperienceTemplate
#
#             - id: sachagreif
#               template: picksTemplate
#
#             - id: smacss
#               template: toolExperienceTemplate
#             - id: it_css
#               template: toolExperienceTemplate
#             - id: cube_css
#               template: toolExperienceTemplate
#
#             - template: sectionOtherToolsTemplate
#
#             - template: happinessTemplate
#
#             - items: [fm-smacss]
#               template: recommendedResourcesTemplate
#
#       - id: css_in_js
#         path: /css-in-js
#         variables:
#             toolIds: ${toolsCategories.css_in_js}
#         blocks:
#             - template: pageIntroductionTemplate
#
#             - template: toolsExperienceRankingTemplate
#
#             - template: toolsSectionStreamsTemplate
#
#             - template: toolsExperienceMarimekkoTemplate
#
#             - template: toolsUsageVariationsTemplate
#
#             - id: styled_components
#               template: toolExperienceTemplate
#             - id: jss
#               template: toolExperienceTemplate
#             - id: styled_jsx
#               template: toolExperienceTemplate
#             - id: radium
#               template: toolExperienceTemplate
#             - id: emotion
#               template: toolExperienceTemplate
#             - id: css_modules
#               template: toolExperienceTemplate
#             - id: styled_system
#               template: toolExperienceTemplate
#
#             - id: hugogiraudel
#               template: picksTemplate
#
#             - id: stitches
#               template: toolExperienceTemplate
#             - id: styletron
#               template: toolExperienceTemplate
#             - id: fela
#               template: toolExperienceTemplate
#             - id: linaria
#               template: toolExperienceTemplate
#             - id: astroturf
#               template: toolExperienceTemplate
#
#             - template: sectionOtherToolsTemplate
#
#             - template: happinessTemplate
#
#             - items: [fm-react]
#               template: recommendedResourcesTemplate
#
# - id: tools_others
#   path: /other-tools
#   blocks:
#       - id: tools_others_intro
#         template: pageIntroductionTemplate
#
#       - id: utilities
#         template: otherToolsTemplate
#
#       - id: utilities_others
#         template: otherToolsFreeFormTemplate
#
#       - id: text_editors
#         template: otherToolsTemplate
#
#       - id: foolip
#         template: picksTemplate
#
#       - id: text_editors_others
#         template: otherToolsFreeFormTemplate
#
#       - id: browsers
#         template: otherToolsTemplate
#
#       - id: browsers_others
#         template: otherToolsFreeFormTemplate
#
#       - items: [fm-storybook]
#         template: recommendedResourcesTemplate
#
# - id: environments
#   path: /environments
#   blocks:
#       - template: pageIntroductionTemplate
#
#       - id: browsers
#         template: environmentTemplate
#
#       - id: form_factors
#         translateData: true
#         template: environmentTemplate
#
#       - id: css_for_print
#         template: environmentRatingTemplate
#
#       - id: css_for_email
#         template: environmentRatingTemplate
#
# - id: resources
#   path: /resources
#   blocks:
#       - template: pageIntroductionTemplate
#
#       - id: blogs_news_magazines
#         template: resourcesTemplate
#
#       - id: blogs_news_magazines_others
#         template: resourcesFreeFormTemplate
#
#       - id: sites_courses
#         template: resourcesTemplate
#
#       - id: 5t3ph
#         template: picksTemplate
#
#       - id: sites_courses_others
#         template: resourcesFreeFormTemplate
#
#       - id: podcasts
#         template: resourcesTemplate
#
#       - id: podcasts_others
#         template: resourcesFreeFormTemplate
#
# - id: opinions
#   path: /opinions
#   blocks:
#       - template: pageIntroductionTemplate
#
#       - id: css_easy_to_learn
#         template: opinionTemplate
#
#       - id: css_evolving_slowly
#         template: opinionTemplate
#
#       - id: utility_classes_to_be_avoided
#         template: opinionTemplate
#
#       - id: selector_nesting_to_be_avoided
#         template: opinionTemplate
#
#       - id: jina
#         template: picksTemplate
#
#       - id: css_is_programming_language
#         template: opinionTemplate
#
#       - id: enjoy_writing_css
#         template: opinionTemplate
#
#       - id: state_of_the_web
#         template: opinionHappinessTemplate
#
#       - id: state_of_css
#         template: opinionHappinessTemplate
#
#       - id: currently_missing_from_css
#         template: opinionsOthersTemplate
#
# - id: awards
#   path: /awards
#   blocks:
#       - template: pageIntroductionTemplate
#
#       - id: feature_adoption_delta_award
#         blockType: AwardBlock
#         enableExport: true
#         awards:
#             - id: grid
#               value: '+18.6%'
#             - id: object_fit
#               value: '+17.8%'
#             - id: variables
#               value: '+15.2%'
#
#       - id: tool_usage_delta_award
#         blockType: AwardBlock
#         enableExport: true
#         awards:
#             - id: tailwind_css
#               value: '+17.8%'
#             - id: atomic_css
#               value: '+10.8%'
#             - id: css_modules
#               value: '+10.1%'
#
#       - id: tool_satisfaction_award
#         blockType: AwardBlock
#         enableExport: true
#         awards:
#             - id: post_css
#               value: '91.4%'
#             - id: css_modules
#               value: '86.8%'
#             - id: tailwind_css
#               value: '86.6%'
#
#       - id: tool_interest_award
#         blockType: AwardBlock
#         enableExport: true
#         awards:
#             - id: css_modules
#               value: '75.1%'
#             - id: tailwind_css
#               value: '62%'
#             - id: styled_components
#               value: '60%'
#
#       - id: most_write_ins_award
#         blockType: AwardBlock
#         enableExport: true
#         awards:
#             - id: phpstorm
#               value: '200'
#             - id: udemy
#               value: '159'
#             - id: frontendmasters
#               value: '112'
#
#       # - id: prediction_award
#       #   blockType: AwardBlock
#       #   awards:
#       #       - id: svelte
#       #       - id: nest
#       #       - id: stencil
#
#       # - id: best_blog_award
#       #   blockType: AwardBlock
#       #   awards:
#       #       - id: svelte
#       #       - id: nest
#       #       - id: stencil
#
#       # - id: best_article_award
#       #   blockType: AwardBlock
#       #   awards:
#       #       - id: svelte
#       #       - id: nest
#       #       - id: stencil

- id: conclusion
  path: /conclusion
  blocks:
      - id: conclusion
        blockType: ConclusionBlock
      - id: conclusion_newsletter
        blockType: NewsletterBlock

# note: other pages need to be included in the sitemap too so they can get the proper
# locale passed to them

- id: support
  path: /support
  is_hidden: true
  blocks:
      - id: support
        template: pageIntroductionTemplate

- id: notfound
  titleId: notfound.title
  path: /404
  is_hidden: true
  blocks:
      - id: notfound
        blockType: NotFoundBlock
